### ISSUE TITLE
SR04 Erratas

### ISSUE THREAD

**Issue by marikisthar** [Ygoproco/Live2017#108]
[SR04] Japanese Text Updates`
February 27, 2017 NeoArkadia

5 cards from the 4th Structure Deck R got text updates that modify how they play slightly here and there. Keep in mind for the moment these changes are restricted to Japan for the moment.

Ultimate Tyranno
(1) During your Battle Phase, if “Ultimate Tyranno” can attack, monsters other than “Ultimate Tyranno” cannot attack.
(2) This card can attack all monsters your opponent controls once each.

(1) means that Ultimate Tyranno must be the first to attack.
(2) adds “can”, preventing toxic infinite attack loop issues this card has had in the past, as demonstrated by this card’s use in the GX animated series where it got caught in an infinite attack loop against “Rescueroid”, “Ambulanceroid”, “Decoyroid” and “Cyber Summon Blaster”.

Specifically it means you can choose to attack multiple monsters, but you are not required to.

Gilasaurus
(1) You can Special Summon this card (from your hand)
(2) If this card is Special Summoned by its (1) effect: Activate this effect; your opponent can Special Summon 1 monster from their Graveyard.

Specifically what happened here is Gilasaurus is an If mandatory, but it no longer makes your opponent target. Your opponent can still choose to or not to Summon a monster of their own free will and volition.

Big Evolution Pill
Tribute 1 Dinosaur-Type monster you control to activate this card. After this card is activated, it remains on the field, and is destroyed during the End Phase of your opponent’s 3rd turn, counting by your opponent’s turn.
(1) If this card is present in a Spell & Trap Zone, you can Normal Summon Level 5 or higher Dinosaur-Type monsters without a Tribute.

The major clarification with this text is telling you how to count when it’s destroyed, no real effect change, just making it less obtuse and difficult to understand.

Swords of Concealing Light
After this card activated, destroy it during your 2nd Standby Phase.
(1) As the effect resolves when this card is activated, if there are face-up monsters on your opponent’s field, change all of those monsters to face-down Defense Position.
(2) While this card remains in your Spell & Trap Card Zone, monsters on the opponent’s field cannot change their Battle Positions.

Basically this new text plus rulings in Japan force a reversal to the ruling issued at World Championship 2016 last year, as regardless of when a monster appeared, it gets turned face-down for Swords.

Fossil Excavation
(1) Discard 1 card, then target 1 Dinosaur-Type monster in your Graveyard; Special Summon that Dinosaur-Type monster.
(2) While this card is remains present in a Spell & Trap Zone, the monster Special Summoned by this card’s (1) effect has its effects negated, and is destroyed if this card leaves the field. When that monster is destroyed, destroy this card.

This one basically implies if by some freak of nature Konami printed say Eternal Reverse, and let you Set Fossil Excavation again, the monster Special Summoned by Excavation would regain its effects. No real massive change, but…

Thanks to Eva for pointing these out. Further explanations and clarifications for these cards should come up in upcoming Ruling related posts.

https://ygorganization.com/kenzanshotfirst/

**Comment by marikisthar** [comment]
could you update some SR04 cards above???

**Comment by MichaelLawrenceDee** [comment]
This can be closed.
