### ISSUE TITLE
White Wing Magician not treated as Synchro Tuner monster

### ISSUE THREAD

**Issue by ghost** [Ygoproco/Live2017#117]
When trying to summon Cosmic Blazar Dragon with White Wing Magician + Lv. 8 non-Tuner Synchro monster + Limit Overdrive, White Wing Magician is not considered a Synchro Tuner Monster.

Same problem happens when trying summon Stardust Chronicle Spark dragon by using White Wing Magician + Lv. 6 non-Tuner synchro monster.

Please fix.

Thanks

**Comment by AndreOliveiraMendes** [comment]
but it not a synchro monster, it treated as "synchro dragon" (archetype) is not same as treated as synchro dragon (type synchro+race dragon)

**Comment by ghost** [comment]
Oh, I had not noticed. Thanks
