### ISSUE TITLE
Trickster Lightstage issues

### ISSUE THREAD

**Issue by TharmB** [Ygoproco/Live2017#126]
When using Trickster Lightstage's Second Effect (Once per turn: You can target 1 Set card in your opponent's Spell & Trap Zone; while this card is face up on the field, that Set card cannot be activated until the End Phase, also during that End Phase, your opponent must activate it or send it to the Graveyard) does not force activation or grave sending when dueling the AI. Checking if it works at all now.

Edit: Tested over Lan. Effect prevents targeted card from activating once applied (Can still activate in response, which is right), however nothing happens when the end phase effect attempts to resolve.

Edit 2: Further testing, the effect keeps attempting to resolve every endphase.

**Comment by TharmB** [comment]
Fixed as of latest patch, Thank you very much!

**Comment by TharmB** [comment]
Turns out it's not fully fixed, having issues when "activate" is chosen for spells! Card is flipped face up, but does not resolve or leave the field. Happens with both quick play and normal spells, cannot confirm if happens for traps at current time.

**Comment by KServantes** [comment]
@TharmB you can close this. I tested and it works with quick play, normal spells, and traps. They're sent to the Grave after they can or can't activate. Tested with Shrink, Terraforming, and Fiendish Chain.

**Comment by TharmB** [comment]
Wasn't aware they'd fixed it, seems to be working fine now though, like you said. Closing.
