### ISSUE TITLE
Missing D/D/D High Executive Genghis and other beta cards. 

### ISSUE THREAD

**Issue by azispratama92** [Ygoproco/Live2017#309]
Hello, this morning i just run $git pull command and suddenly all the beta cards, and some of the expansions cards are missing, i can still see the cards image but the cards name and the text data is missing, only showing `???`

Any clue how to fix it ? Many Thanks ^ ^ 

I'm running YGO Pro on Linux Box.

**Comment by hah4sk** [comment]
Hey is this problem still happening? If so I'll try to help with it :D

**Comment by azispratama92** [comment]
already solved, but thanks anyway, =)

I just deleted the expansions folders, and re-run the git pull command in my linux box. But if the problems still persist, used the Data Editor X instead to manually add new entry for the cards (will works on online server). I hope it will help the fellow YGO Pro Linux gamer =)
