### ISSUE TITLE
Want to stop refresh the files on this folder when I launch ygopro.exe

### ISSUE THREAD

**Issue by ortixxx** [Ygoproco/Live2017#471]
Hi, my name is Luis and I hope you can help us.
My friends and I want to modify the 'lflist.config' file just for play against eachother in a custom banlist like PRE-sept2012 or something like that, obiously I know how edit the banlist, BUT when that file is modify and ygopro.exe is launcher again the file is refreshes as the repository are.

--->https://github.com/Ygoproco/Live2017

There are a way to stop that refresh?
Only for us, trust me, I'm the only one that played yugioh before and i'm tired of that.
Thank you c:

**Comment by AndreOliveiraMendes** [comment]
@ortixxx inside you game folder there a file called system.conf
go to line where it say
ignore_instant_updates = 0
and change the value to either 1 or 2 (not sure wich)
it should stop rewriting files in these folder's

**Comment by ortixxx** [comment]
many thaks, actually we resolved it yesterday


right valor is "-1"

Now we are deleting cards from .cdb file , there are to many expansion . . .


________________________________
De: AndreOliveiraMendes <notifications@github.com>
Enviado: jueves, 3 de agosto de 2017 01:06 a. m.
Para: Ygoproco/Live2017
CC: ortiz; Mention
Asunto: Re: [Ygoproco/Live2017] Want to stop refresh the files on this folder when I launch ygopro.exe (#471)


@ortixxx<https://github.com/ortixxx> inside you game folder there a file called system.conf
go to line where it say
ignore_instant_updates = 0
and change the value to either 1 or 2 (not sure wich)
it should stop rewriting files in these folder's
