### ISSUE TITLE
Some bugs of scritps

### ISSUE THREAD

**Issue by mist714** [Ygoproco/Live2017#8]
* "Superheavy samurai ninja shinobiashi" is not treated as a "ninja" monster
* Cannot conduct battle by "equip shot" involving "Phantasmal Lord Ultimitl Bishbaalkin",which used its effect

**Comment by KServantes** [comment]
Submitted pull #46 to fix these two.

**Comment by TheOnePharaoh** [comment]
@mist714 Why isn't this closed yet?
